version: '2'
services:
  db:
    image: mysql:5.7.11
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
  worker:
    build:
      context: .
      dockerfile: Dev-Dockerfile
    command: bundle exec foreman start --formation worker=1
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db